apiVersion: v1
kind: Service
metadata:
  namespace: demo
  labels:
    app: demo
  name: demo
spec:
  ports:
  
    - protocol: TCP
      port: 4477
      targetPort: 4477
   
   
  selector:
    app: demo
  type: ClusterIP
